import type { PracticeText } from './types.ts'

export const en: PracticeText = {
  scenarios: {
    cold_food: {
      opening: 'Excuse me. My lamb is lukewarm, and we waited forty minutes for it.',
      calm: 'Okay, thank you. But I really don’t want to wait another forty minutes. How long will a new one take?',
      upset: 'That’s it? We’ve sat here for forty minutes and that’s all you can say?',
      resolved: 'Alright, that’s fair. Thank you for sorting it out so quickly.',
      walkout: 'Forget it. Just bring the bill, we’re leaving.',
      ideal: [
        'I’m so sorry, it shouldn’t arrive like that. Let me take it back and have a fresh, hot one made for you right away; it’ll be with you in about 10 minutes.',
        'Completely fair. I’ve asked the kitchen to put it first in line, so about 10 minutes. I’ll bring some bread and a top-up while you wait, and check back in five.',
      ],
    },
    long_wait: {
      opening: 'It’s been half an hour since we ordered. Is anything actually happening?',
      calm: 'Okay. We have a show at nine, though. Will we make it?',
      upset: 'You’re not even telling us anything. Should we just go somewhere else?',
      resolved: 'Okay, that helps. Thanks for being straight with us.',
      walkout: 'We’re going. This is ridiculous.',
      ideal: [
        'I’m really sorry for the wait, and for not updating you sooner. Let me check with the kitchen right now and come straight back with an exact time.',
        'Yes, you’ll make it. Your mains will be out in about 8 minutes, and I’ll have the bill ready the moment you ask, so you can leave by 8:40.',
      ],
    },
    sold_out: {
      opening: 'The risotto is off? That’s the whole reason we came tonight.',
      calm: 'Okay… what would you have instead, honestly?',
      upset: 'So we came all this way for nothing. Great.',
      resolved: 'That sounds lovely, actually. Let’s try it.',
      walkout: 'I’ve lost my appetite. We’ll just have drinks.',
      ideal: [
        'I’m so sorry. I completely understand how disappointing that is when you came for it. Can I suggest something close that the chef is really proud of tonight?',
        'Honestly, the pumpkin gnocchi: creamy and rich like the risotto, with sage butter. If you’d prefer, I’ll ask the chef what else they can make for you.',
      ],
    },
    allergy: {
      opening: 'I have a severe nut allergy. Is the biryani safe for me?',
      calm: 'Okay, thank you for checking. What could I have instead?',
      upset: 'You “think” so? I need to be sure. This could put me in hospital.',
      resolved: 'Thank you. I feel much safer knowing the chef has checked.',
      walkout: 'I don’t feel safe eating here. We’ll leave it.',
      ideal: [
        'Thank you for telling me. I won’t guess with a nut allergy: the biryani does contain nuts, and I’ll confirm everything else with the chef before you order.',
        'The chef confirms the sea bass and the burrata have no nuts and can be prepared separately. I’ll mark your allergy on the ticket so the kitchen sees it.',
      ],
    },
    rude: {
      opening: 'Hey, you! We’ve been waving for ages. Do you even work here?',
      calm: 'Fine. Just bring the bill. Now.',
      upset: 'Unbelievable. Get me someone who actually knows what they’re doing.',
      resolved: '…Okay. Thanks. Sorry for snapping.',
      walkout: 'Get me the manager. Now.',
      ideal: [
        'I’m sorry you’ve been waiting, that’s not okay. I’m here now. What can I get for you?',
        'Of course. I’ll bring the bill right away, in about two minutes. Is there anything that went wrong tonight I should pass on?',
      ],
    },
    wrong_bill: {
      opening: 'This bill has two desserts on it that we never ordered.',
      calm: 'Okay. This is the second mistake tonight, though.',
      upset: 'Are you trying to charge us for things we didn’t have?',
      resolved: 'Okay, thank you. That’s sorted, then.',
      walkout: 'I’m not paying until I speak to the manager.',
      ideal: [
        'I’m so sorry about that, and thank you for catching it. Let me take those off and bring you a corrected bill right away.',
        'You’re right, and I’m sorry tonight hasn’t been smooth. Here’s the corrected bill; I’ve also told my manager so we can make it right.',
      ],
    },
    access_direct: {
      opening: '(The guest uses a wheelchair. You asked their friend what they’d like.) Excuse me, you can ask me. I’m the one ordering.',
      calm: 'Thank you. And is there a step on the way to the restroom?',
      upset: 'You did it again. I’m right here.',
      resolved: 'Perfect, thank you. That’s really helpful.',
      walkout: 'Never mind. We’ll eat somewhere else next time.',
      ideal: [
        'I’m sorry, you’re absolutely right. What would you like to order?',
        'There’s a step-free route to the accessible restroom just past the bar. I’ll show you the way whenever you’re ready.',
      ],
    },
    fasting: {
      opening: 'I’m fasting for Navratri, so no grains, onion or garlic tonight. What can I actually eat here?',
      calm: 'That helps. Can the kitchen make something specially?',
      upset: '“Just a little onion won’t matter”? It matters to me.',
      resolved: 'Thank you for taking it seriously. That’s lovely.',
      walkout: 'I’ll just have water, then.',
      ideal: [
        'Thank you for telling me. May I ask if there’s anything else you avoid, like regular salt or certain oils? I’ll check with the chef what they can make for you.',
        'The chef can make sabudana tikki with sendha namak, and a fruit plate: no grains, onion or garlic. Would that work for you?',
      ],
    },
    misgender: {
      opening: '(You said “sir”.) Actually, it’s “ma’am”. Or just my name, Priya.',
      calm: 'It happens. Could we see the dessert menu?',
      upset: 'That’s the second time tonight. It’s not that hard.',
      resolved: 'Thank you. The kulfi sounds good.',
      walkout: 'Just the bill, please.',
      ideal: ['Sorry, Priya, thank you for telling me. What can I get you?', 'Of course, here you are, Priya. The pistachio kulfi is lovely tonight if you’d like something light.'],
    },
    m_guest: {
      opening: 'Are you the manager? Our server ignored us for twenty minutes and then got our order wrong. This is unacceptable.',
      calm: 'Fine. But I don’t want that server at our table again.',
      upset: 'So you’re just going to defend your staff? Typical.',
      resolved: 'Thank you for actually listening. We’ll stay for dessert.',
      walkout: 'I’ll be writing a review about this.',
      ideal: [
        'I’m the floor manager, and I’m sorry. Please tell me what happened, from the start.',
        'I understand. I’ll look after your table myself for the rest of the evening. Your correct dish will be out in 10 minutes, and dessert is on us tonight.',
      ],
    },
    m_feedback: {
      opening: 'You wanted to see me? Is this about the bills taking long? Section A was packed tonight.',
      calm: 'Okay. What should I do differently?',
      upset: 'So it’s my fault now? I had five tables on my own.',
      resolved: 'That’s fair. Thanks for listening. I’ll try it tomorrow.',
      walkout: 'Whatever. Can I go back to my tables?',
      ideal: [
        'Thanks for coming over; let’s have a quick word in private. You’re right, A was packed. Tonight I noticed the bill at T4 took about 10 minutes after they asked. Walk me through what happened.',
        'Let’s try printing the bill when desserts are cleared, and I’ll move a table to Rohan when you’re over four. Let’s check in after Friday’s service.',
      ],
    },
    m_harassed: {
      opening: 'The man at T6 keeps grabbing my arm and making comments. I don’t want to go back there.',
      calm: 'But they’re regulars. Won’t I get in trouble?',
      upset: 'So I just have to put up with it?',
      resolved: 'Thank you. I really thought you’d tell me to ignore it.',
      walkout: 'Forget I said anything.',
      ideal: [
        'Are you okay? Thank you for telling me, and it’s not your fault. You won’t go back to T6; I’ll take it myself.',
        'No, you won’t get in trouble. Nobody has to put up with that, regulars or not. I’ll speak to them, and we’ll check in after service about whether you want to report it.',
      ],
    },
    m_conflict: {
      opening: 'Rohan keeps taking tables from my section and the tips that come with them. It’s not fair and I’m done being polite about it.',
      calm: 'So what are you going to do about it?',
      upset: 'Of course you’re on his side.',
      resolved: 'Okay. A clear rule would help. Thanks.',
      walkout: 'Fine. I’ll sort it out with him myself.',
      ideal: [
        'Thanks for telling me. Let’s talk privately after service. Tell me what’s been happening, with a couple of examples.',
        'I’ll talk to Rohan too. Then the three of us will agree one clear rule for seating and tips, and we’ll check in next week to see it’s working.',
      ],
    },
    m_newhire: {
      opening: 'Sorry… I’m new and my English isn’t good. Everything is so fast tonight, I keep forgetting things.',
      calm: 'Maybe this job is not for me.',
      upset: 'Everyone is looking at me. I’m making it worse.',
      resolved: 'Okay. Thank you. I’ll try again.',
      walkout: 'I think I should go home.',
      ideal: [
        'You’re doing fine; it’s your first rush and everyone finds it hard. Take two minutes and drink some water. I’ll take T7 for now.',
        'It is for you; you just need time. Tomorrow you’ll have a smaller section and a buddy who speaks your language, and we’ll check in after every shift this week.',
      ],
    },
    m_allergy: {
      opening: 'My husband’s lips are swelling. He told the waiter he’s allergic to nuts! What was in that kebab?',
      calm: 'Is someone calling an ambulance?',
      upset: 'Why is nobody doing anything?!',
      resolved: 'Thank you for staying with us. The paramedics are here.',
      walkout: 'We’re going to the hospital ourselves.',
      ideal: [
        'I’m calling 112 for an ambulance right now. Does he have an adrenaline pen? Let’s help him use it and lay him down.',
        'Yes, the ambulance is on its way and someone is waiting at the door for it. I’m staying right here with you.',
      ],
    },
  },
  push: { guest: 'I’m still waiting to hear what you’re actually going to do.', staff: 'Okay… so what happens now?' },
  grudging: { guest: 'Fine. Let’s just leave it there.', staff: 'Okay. I guess.' },
  checks: {
    sorry: { good: 'You apologised.', tip: 'Start with a sincere sorry, even if it wasn’t your fault.' },
    empathy: { good: 'You showed you understood how they feel.', tip: 'Name the feeling: “I completely understand, that’s frustrating.”' },
    action: { good: 'You offered a clear next step.', tip: 'Say exactly what you’ll do next: “Let me replace it right away.”' },
    time: { good: 'You gave a time.', tip: 'Give a time, so the wait feels shorter: “in about 5 minutes”.' },
    blame: { good: '', tip: 'Leave the kitchen out of it. The guest wants it fixed, not who caused it.' },
    confirm: { good: 'You checked with the kitchen instead of guessing.', tip: 'Never promise a dish is safe from memory. Say you’ll confirm with the chef.' },
    guess: { good: '', tip: 'Don’t guarantee safety yourself; let the kitchen confirm.' },
    direct: { good: 'You spoke to the guest directly.', tip: 'Speak to the guest themselves, not only to the person with them.' },
    ask: { good: 'You asked instead of assuming.', tip: 'Ask kindly what they eat or need: rules differ from person to person.' },
    judge: { good: '', tip: 'Never question or comment on someone’s faith, diet or disability.' },
    listen: { good: 'You listened before acting.', tip: 'Start by listening: “Tell me what happened.”' },
    own: { good: 'You took ownership.', tip: 'Introduce yourself and take ownership: “I’m the manager; I’ll sort this out.”' },
    private: { good: 'You kept it private.', tip: 'Move the conversation somewhere private, away from guests and the team.' },
    specific: { good: 'You were specific about what happened.', tip: 'Be specific: when, which table, what happened, and the effect.' },
    support: { good: 'You looked after the person first.', tip: 'Check on the person first: “Are you okay? It wasn’t your fault.”' },
    follow: { good: 'You agreed a follow-up.', tip: 'Agree a next step and when you’ll check in.' },
    emergency: { good: 'You treated it as an emergency straight away.', tip: 'Act first: call 112 for an ambulance and help them use their own adrenaline auto-injector.' },
    shame: { good: '', tip: 'Talk about the work, not the person; avoid “always”, “never” and labels.' },
    short: { good: '', tip: 'Say a little more: a full, calm sentence reassures them.' },
  },
  debrief: {
    worked: 'What worked',
    practise: 'To practise',
    keep: 'Keep doing exactly this.',
    won: 'You won them over.',
    lost: 'They left unhappy. Try again using the ideal replies.',
    ok: 'It ended, but they weren’t fully won over.',
    noReplies: 'Reply at least once, then I can give you feedback.',
  },
}
