import type { PracticeText } from './types.ts'

export const es: PracticeText = {
  scenarios: {
    cold_food: {
      opening: 'Disculpe. Mi cordero está tibio, y lo esperamos cuarenta minutos.',
      calm: 'Vale, gracias. Pero no quiero esperar otros cuarenta minutos. ¿Cuánto tardará uno nuevo?',
      upset: '¿Eso es todo? Llevamos cuarenta minutos aquí sentados, ¿y solo me dice eso?',
      resolved: 'Vale, me parece justo. Gracias por solucionarlo tan rápido.',
      walkout: 'Déjelo. Tráiganos la cuenta, nos vamos.',
      ideal: [
        'Lo siento muchísimo, no debería llegar así. Me lo llevo y pido que le preparen uno recién hecho y caliente ahora mismo; lo tendrá en unos 10 minutos.',
        'Tiene toda la razón. He pedido a cocina que lo prepare el primero, unos 10 minutos. Mientras tanto le traigo pan y algo de beber, y vuelvo a ver cómo va en cinco.',
      ],
    },
    long_wait: {
      opening: 'Hace media hora que pedimos. ¿Está pasando algo?',
      calm: 'Vale. Pero tenemos un espectáculo a las nueve. ¿Llegaremos?',
      upset: 'Ni siquiera nos dice nada. ¿Nos vamos a otro sitio?',
      resolved: 'Vale, eso ayuda. Gracias por hablarnos claro.',
      walkout: 'Nos vamos. Esto es ridículo.',
      ideal: ['Siento mucho la espera, y no haberles avisado antes. Voy ahora mismo a cocina y vuelvo con una hora exacta.', 'Sí, llegarán. Sus principales saldrán en unos 8 minutos y tendré la cuenta lista en cuanto la pidan, para que puedan salir a las 8:40.'],
    },
    sold_out: {
      opening: '¿No queda risotto? Es justo por lo que vinimos esta noche.',
      calm: 'Vale… ¿qué pediría usted en su lugar, sinceramente?',
      upset: 'O sea, que vinimos hasta aquí para nada. Genial.',
      resolved: 'Eso suena muy bien, la verdad. Vamos a probarlo.',
      walkout: 'Se me han quitado las ganas. Solo tomaremos algo de beber.',
      ideal: ['Lo siento mucho. Entiendo perfectamente lo decepcionante que es cuando venían por eso. ¿Puedo sugerirles algo parecido de lo que el chef está muy orgulloso esta noche?', 'Sinceramente, los ñoquis de calabaza: cremosos e intensos como el risotto, con mantequilla de salvia. Si lo prefieren, pregunto al chef qué más puede prepararles.'],
    },
    allergy: {
      opening: 'Tengo una alergia grave a los frutos secos. ¿El biryani es seguro para mí?',
      calm: 'Vale, gracias por comprobarlo. ¿Qué podría tomar en su lugar?',
      upset: '¿"Cree" que sí? Necesito estar segura. Podría acabar en el hospital.',
      resolved: 'Gracias. Me siento mucho más tranquila sabiendo que lo ha comprobado el chef.',
      walkout: 'No me siento segura comiendo aquí. Lo dejamos.',
      ideal: ['Gracias por decírmelo. Con una alergia a frutos secos no voy a suponer nada: el biryani lleva frutos secos, y confirmaré todo lo demás con el chef antes de que pida.', 'El chef confirma que la lubina y la burrata no llevan frutos secos y pueden prepararse aparte. Anoto su alergia en la comanda para que cocina la vea.'],
    },
    rude: {
      opening: '¡Oiga, usted! Llevamos un siglo haciendo señas. ¿Trabaja aquí o qué?',
      calm: 'Bien. Tráigame la cuenta. Ya.',
      upset: 'Increíble. Que venga alguien que sepa lo que hace.',
      resolved: '…Vale. Gracias. Perdone por hablarle así.',
      walkout: 'Quiero hablar con la gerencia. Ahora.',
      ideal: ['Siento que hayan tenido que esperar, no está bien. Ya estoy aquí. ¿Qué les traigo?', 'Por supuesto. Le traigo la cuenta ahora mismo, en unos dos minutos. ¿Ha habido algo esta noche que deba comunicar?'],
    },
    wrong_bill: {
      opening: 'Esta cuenta tiene dos postres que no hemos pedido.',
      calm: 'Vale. Pero es el segundo error de la noche.',
      upset: '¿Nos están cobrando cosas que no hemos tomado?',
      resolved: 'Vale, gracias. Entonces ya está resuelto.',
      walkout: 'No pago hasta hablar con la gerencia.',
      ideal: ['Lo siento muchísimo, y gracias por darse cuenta. Los quito y le traigo la cuenta corregida ahora mismo.', 'Tiene razón, y siento que la noche no haya ido bien. Aquí tiene la cuenta corregida; también se lo he comunicado a mi responsable para compensarles.'],
    },
    access_direct: {
      opening: '(La persona usa silla de ruedas. Usted preguntó a quien la acompaña.) Disculpe, puede preguntarme a mí. Soy yo quien pide.',
      calm: 'Gracias. ¿Y hay algún escalón de camino al baño?',
      upset: 'Lo ha vuelto a hacer. Estoy aquí mismo.',
      resolved: 'Perfecto, gracias. Me ayuda mucho.',
      walkout: 'Da igual. La próxima vez comeremos en otro sitio.',
      ideal: ['Disculpe, tiene toda la razón. ¿Qué le gustaría pedir?', 'Hay un camino sin escalones hasta el baño accesible, justo pasada la barra. Le acompaño cuando quiera.'],
    },
    fasting: {
      opening: 'Estoy en ayuno por Navratri, así que esta noche nada de cereales, cebolla ni ajo. ¿Qué puedo comer aquí?',
      calm: 'Eso ayuda. ¿Puede la cocina preparar algo especial?',
      upset: '"¿Un poquito de cebolla no pasa nada?" Para mí sí pasa.',
      resolved: 'Gracias por tomárselo en serio. Es todo un detalle.',
      walkout: 'Entonces solo tomaré agua.',
      ideal: ['Gracias por decírmelo. ¿Puedo preguntarle si evita algo más, como la sal común o algunos aceites? Pregunto al chef qué puede prepararle.', 'El chef puede hacer tikki de sabudana con sal de roca y un plato de fruta: sin cereales, cebolla ni ajo. ¿Le parece bien?'],
    },
    misgender: {
      opening: '(Usted dijo "señor".) En realidad es "señora". O simplemente mi nombre, Priya.',
      calm: 'Pasa. ¿Podemos ver la carta de postres?',
      upset: 'Es la segunda vez esta noche. No es tan difícil.',
      resolved: 'Gracias. El kulfi tiene buena pinta.',
      walkout: 'Solo la cuenta, por favor.',
      ideal: ['Perdón, Priya, gracias por decírmelo. ¿Qué le traigo?', 'Claro, aquí tiene, Priya. Si le apetece algo ligero, el kulfi de pistacho está buenísimo esta noche.'],
    },
    m_guest: {
      opening: '¿Es usted quien está al cargo? Nuestro camarero nos ignoró veinte minutos y luego se equivocó con el pedido. Es inaceptable.',
      calm: 'Bien. Pero no quiero que esa persona vuelva a nuestra mesa.',
      upset: '¿O sea que va a defender a su personal y ya está? Lo típico.',
      resolved: 'Gracias por escucharnos de verdad. Nos quedamos al postre.',
      walkout: 'Voy a escribir una reseña sobre esto.',
      ideal: ['Soy responsable de sala, y lo siento. Cuénteme qué ha pasado, desde el principio.', 'Lo entiendo. Me encargaré personalmente de su mesa el resto de la noche. Su plato correcto saldrá en 10 minutos, y el postre corre de nuestra cuenta.'],
    },
    m_feedback: {
      opening: '¿Querías verme? ¿Es por las cuentas que tardan? La sección A estaba a tope esta noche.',
      calm: 'Vale. ¿Qué debería hacer diferente?',
      upset: '¿Así que ahora es culpa mía? Tenía cinco mesas yo sola.',
      resolved: 'Me parece justo. Gracias por escucharme. Lo probaré mañana.',
      walkout: 'Lo que sea. ¿Puedo volver a mis mesas?',
      ideal: ['Gracias por venir; hablemos un momento en privado. Tienes razón, A estaba a tope. Esta noche vi que la cuenta de la T4 tardó unos 10 minutos desde que la pidieron. Cuéntame qué pasó.', 'Probemos a imprimir la cuenta al retirar los postres, y cuando tengas más de cuatro mesas paso una a Rohan. Lo revisamos después del servicio del viernes.'],
    },
    m_harassed: {
      opening: 'El hombre de la T6 no para de agarrarme del brazo y de hacer comentarios. No quiero volver a esa mesa.',
      calm: 'Pero son clientes habituales. ¿No me meteré en un lío?',
      upset: '¿O sea que tengo que aguantarlo?',
      resolved: 'Gracias. Pensaba que me dirías que lo ignorara.',
      walkout: 'Olvida lo que he dicho.',
      ideal: ['¿Estás bien? Gracias por decírmelo, y no es tu culpa. No vas a volver a la T6; la atiendo yo.', 'No, no te vas a meter en ningún lío. Sean habituales o no, nadie tiene que aguantar eso. Hablaré con ellos, y después del servicio hablamos de si quieres denunciarlo.'],
    },
    m_conflict: {
      opening: 'Rohan no para de quitarme mesas de mi sección y las propinas que vienen con ellas. No es justo y se me acabó la paciencia.',
      calm: '¿Y qué vas a hacer al respecto?',
      upset: 'Claro, tú estás de su lado.',
      resolved: 'Vale. Una regla clara ayudaría. Gracias.',
      walkout: 'Bien. Ya lo arreglaré yo con él.',
      ideal: ['Gracias por contármelo. Hablemos en privado después del servicio. Cuéntame qué está pasando, con un par de ejemplos.', 'Hablaré también con Rohan. Luego los tres acordamos una regla clara para asignar mesas y propinas, y la semana que viene revisamos si funciona.'],
    },
    m_newhire: {
      opening: 'Perdona… soy nuevo y mi inglés no es bueno. Todo va muy rápido esta noche, se me olvidan las cosas.',
      calm: 'Quizá este trabajo no es para mí.',
      upset: 'Todos me están mirando. Lo estoy empeorando.',
      resolved: 'Vale. Gracias. Lo intentaré otra vez.',
      walkout: 'Creo que debería irme a casa.',
      ideal: ['Lo estás haciendo bien; es tu primer momento de mucho trabajo y a todo el mundo le cuesta. Tómate dos minutos y bebe agua. Yo me encargo de la T7 por ahora.', 'Sí es para ti; solo necesitas tiempo. Mañana tendrás una sección más pequeña y un compañero que habla tu idioma, y esta semana hablamos después de cada turno.'],
    },
    m_allergy: {
      opening: '¡A mi marido se le están hinchando los labios! Le dijo al camarero que es alérgico a los frutos secos. ¿Qué llevaba ese kebab?',
      calm: '¿Alguien está llamando a una ambulancia?',
      upset: '¡¿Por qué nadie hace nada?!',
      resolved: 'Gracias por quedarse con nosotros. Ya están aquí los sanitarios.',
      walkout: 'Nos vamos al hospital por nuestra cuenta.',
      ideal: ['Estoy llamando ahora mismo al 112 para pedir una ambulancia. ¿Lleva un autoinyector de adrenalina? Ayudémosle a usarlo y tumbémosle.', 'Sí, la ambulancia está en camino y hay alguien esperándola en la puerta. Me quedo aquí con ustedes.'],
    },
  },
  push: { guest: 'Sigo esperando a saber qué va a hacer exactamente.', staff: 'Vale… ¿y ahora qué pasa?' },
  grudging: { guest: 'Bien. Dejémoslo así.', staff: 'Vale. Supongo.' },
  checks: {
    sorry: { good: 'Has pedido disculpas.', tip: 'Empieza con una disculpa sincera, aunque no sea culpa tuya.' },
    empathy: { good: 'Has mostrado que entiendes cómo se siente.', tip: 'Nombra el sentimiento: "Lo entiendo perfectamente, es frustrante."' },
    action: { good: 'Has ofrecido un siguiente paso claro.', tip: 'Di exactamente qué harás: "Se lo cambio ahora mismo."' },
    time: { good: 'Has dado un tiempo.', tip: 'Da un tiempo para que la espera se haga más corta: "en unos 5 minutos".' },
    blame: { good: '', tip: 'Deja a la cocina al margen. El cliente quiere una solución, no un culpable.' },
    confirm: { good: 'Has consultado con cocina en vez de suponer.', tip: 'Nunca prometas de memoria que un plato es seguro. Di que lo confirmarás con el chef.' },
    guess: { good: '', tip: 'No garantices tú la seguridad; deja que cocina lo confirme.' },
    direct: { good: 'Has hablado directamente con el cliente.', tip: 'Habla con el propio cliente, no solo con quien le acompaña.' },
    ask: { good: 'Has preguntado en vez de suponer.', tip: 'Pregunta con amabilidad qué come o necesita: las normas cambian de una persona a otra.' },
    judge: { good: '', tip: 'Nunca cuestiones ni comentes la fe, la dieta o la discapacidad de nadie.' },
    listen: { good: 'Has escuchado antes de actuar.', tip: 'Empieza escuchando: "Cuénteme qué ha pasado."' },
    own: { good: 'Has asumido la responsabilidad.', tip: 'Preséntate y asume la responsabilidad: "Soy responsable de sala; yo me encargo."' },
    private: { good: 'Lo has hablado en privado.', tip: 'Lleva la conversación a un lugar privado, lejos de clientes y del equipo.' },
    specific: { good: 'Has dado detalles concretos de lo que pasó.', tip: 'Sé concreto: cuándo, qué mesa, qué pasó y qué efecto tuvo.' },
    support: { good: 'Primero has cuidado de la persona.', tip: 'Pregunta primero por la persona: "¿Estás bien? No es tu culpa."' },
    follow: { good: 'Habéis acordado un seguimiento.', tip: 'Acordad un siguiente paso y cuándo lo revisaréis.' },
    emergency: { good: 'Lo has tratado como una emergencia desde el primer momento.', tip: 'Actúa primero: llama al 112 para pedir una ambulancia y ayuda a usar su autoinyector de adrenalina.' },
    shame: { good: '', tip: 'Habla del trabajo, no de la persona; evita "siempre", "nunca" y etiquetas.' },
    short: { good: '', tip: 'Di un poco más: una frase completa y tranquila da confianza.' },
  },
  debrief: {
    worked: 'Lo que funcionó',
    practise: 'Para practicar',
    keep: 'Sigue haciéndolo exactamente así.',
    won: 'Te lo has ganado.',
    lost: 'Se fue descontento. Vuelve a intentarlo con las respuestas ideales.',
    ok: 'Terminó, pero no quedó del todo convencido.',
    noReplies: 'Responde al menos una vez y luego te doy feedback.',
  },
}
