import type { RestaurantConfig, Sop } from './types.ts'

export const DEFAULT_SOP: Sop = {
  greetWithinMin: 2,
  orderNudgeAfterMin: 8,
  kitchenDelayToleranceMin: 4,
  pickupWithinMin: 1.5,
  checkbackAfterMin: 3,
  courseCheckAfterMin: 14,
  billPresentWithinMin: 3,
  farewellWithinMin: 2,
  resetWithinMin: 5,
  maxActiveTablesPerServer: 4,
}

export const DEMO_CONFIG: RestaurantConfig = {
  name: 'Saffron House',
  sections: { A: 's_aisha', B: 's_rohan', C: 's_meera', D: 's_kabir', E: 's_tenzin', F: 's_priya' },
  staff: [
    { id: 's_aisha', name: 'Aisha', role: 'server', color: '#e07a5f', languages: ['en', 'hi', 'ur'] },
    { id: 's_rohan', name: 'Rohan', role: 'server', color: '#3d9a8b', languages: ['en', 'hi', 'mr'] },
    { id: 's_meera', name: 'Meera', role: 'server', color: '#8d6cd1', languages: ['en', 'ta', 'ml'] },
    { id: 's_kabir', name: 'Kabir', role: 'server', color: '#2f6fb0', languages: ['en', 'hi', 'pa'] },
    { id: 's_tenzin', name: 'Tenzin', role: 'server', color: '#b5762a', pronouns: 'they/them', languages: ['en', 'ne', 'hi'] },
    { id: 's_priya', name: 'Priya', role: 'server', color: '#c2477a', languages: ['en', 'bn', 'es'] },
    { id: 'k_pass', name: 'Chef Vikram', role: 'kitchen', color: '#d4a24c' },
    { id: 'm_floor', name: 'Floor Manager', role: 'manager', color: '#6b7280' },
  ],
  tables: [
    { id: 'T1', name: 'T1', seats: 2, section: 'A', posTableId: '1', pos: { x: 26, y: 32 } },
    { id: 'T2', name: 'T2', seats: 4, section: 'A', posTableId: '2', pos: { x: 74, y: 32 } },
    { id: 'T3', name: 'T3', seats: 4, section: 'A', posTableId: '3', pos: { x: 26, y: 74 } },
    { id: 'T4', name: 'T4', seats: 6, section: 'A', posTableId: '4', pos: { x: 74, y: 74 } },
    { id: 'T5', name: 'T5', seats: 2, section: 'B', posTableId: '5', pos: { x: 25, y: 40 } },
    { id: 'T6', name: 'T6', seats: 4, section: 'B', posTableId: '6', pos: { x: 75, y: 40 } },
    { id: 'T7', name: 'T7', seats: 4, section: 'B', posTableId: '7', pos: { x: 50, y: 78 } },
    { id: 'T8', name: 'T8', seats: 2, section: 'C', posTableId: '8', pos: { x: 25, y: 35 } },
    { id: 'T9', name: 'T9', seats: 4, section: 'C', posTableId: '9', pos: { x: 75, y: 35 } },
    { id: 'T10', name: 'T10', seats: 8, section: 'C', posTableId: '10', pos: { x: 50, y: 76 } },
    { id: 'T11', name: 'T11', seats: 2, section: 'D', posTableId: '11', pos: { x: 25, y: 38 } },
    { id: 'T12', name: 'T12', seats: 4, section: 'D', posTableId: '12', pos: { x: 75, y: 38 } },
    { id: 'T13', name: 'T13', seats: 4, section: 'D', posTableId: '13', pos: { x: 50, y: 78 } },
    { id: 'T14', name: 'T14', seats: 2, section: 'E', posTableId: '14', pos: { x: 25, y: 35 } },
    { id: 'T15', name: 'T15', seats: 4, section: 'E', posTableId: '15', pos: { x: 75, y: 35 } },
    { id: 'T16', name: 'T16', seats: 6, section: 'E', posTableId: '16', pos: { x: 50, y: 76 } },
    { id: 'T17', name: 'T17', seats: 2, section: 'F', posTableId: '17', pos: { x: 28, y: 50 } },
    { id: 'T18', name: 'T18', seats: 4, section: 'F', posTableId: '18', pos: { x: 72, y: 50 } },
  ],
  menu: [
    { id: 'm_burrata', name: 'Burrata & heirloom tomato', course: 'starter', station: 'cold', prepMin: 6, posItemId: '1001', contains: ['dairy'] },
    { id: 'm_galouti', name: 'Galouti kebab', course: 'starter', station: 'grill', prepMin: 9, posItemId: '1002', contains: ['meat', 'root', 'nuts'] },
    { id: 'm_soup', name: 'Wild mushroom soup', course: 'starter', station: 'hot', prepMin: 7, posItemId: '1003', contains: ['dairy', 'root'] },
    { id: 'm_tikka', name: 'Paneer tikka', course: 'starter', station: 'grill', prepMin: 10, posItemId: '1004', contains: ['dairy', 'root'] },
    { id: 'm_lamb', name: 'Slow-cooked lamb shank', course: 'main', station: 'hot', prepMin: 14, posItemId: '2001', contains: ['meat', 'root', 'alcohol'] },
    { id: 'm_seabass', name: 'Pan-seared sea bass', course: 'main', station: 'grill', prepMin: 16, posItemId: '2002', contains: ['fish', 'dairy'] },
    { id: 'm_risotto', name: 'Truffle risotto', course: 'main', station: 'hot', prepMin: 15, posItemId: '2003', contains: ['dairy', 'root', 'alcohol'] },
    { id: 'm_biryani', name: 'Dum biryani', course: 'main', station: 'hot', prepMin: 12, posItemId: '2004', contains: ['meat', 'nuts', 'dairy', 'root'] },
    { id: 'm_gnocchi', name: 'Pumpkin gnocchi', course: 'main', station: 'hot', prepMin: 13, posItemId: '2005', contains: ['gluten', 'dairy', 'egg', 'root'] },
    { id: 'm_fondant', name: 'Chocolate fondant', course: 'dessert', station: 'pastry', prepMin: 11, posItemId: '3001', contains: ['gluten', 'dairy', 'egg'] },
    { id: 'm_kulfi', name: 'Pistachio kulfi', course: 'dessert', station: 'pastry', prepMin: 4, posItemId: '3002', contains: ['dairy', 'nuts'] },
    { id: 'm_brulee', name: 'Saffron crème brûlée', course: 'dessert', station: 'pastry', prepMin: 6, posItemId: '3003', contains: ['dairy', 'egg'] },
  ],
  sop: DEFAULT_SOP,
}
